version: '3.9'

volumes:
    mongo-data: {}

services:
    app:
        image: ghcr.io/se-ws22-ihnn/ihnn:latest
        restart: unless-stopped
        expose:
            - 80
        environment:
            - APP_DB_HOST=mongodb
            - APP_DB_USER=root
            - APP_DB_PASS=password
        depends_on:
            - api

    api:
        image: ghcr.io/se-ws22-ihnn/ihnn-api:latest
        restart: unless-stopped
        expose:
            - 3000
        environment:
            - MONGO=${MONGO_URI}
        links:
            - mongo
        depends_on:
            - mongo

    mongo:
        image: mongo
        restart: unless-stopped
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=password
        volumes:
            - mongo-data:/data/db
